frontend:
	bash components/frontend.sh

cart:
	bash components/cart.sh

user:
	bash components/user.sh

catalogue:
	bash components/catalogue.sh

shipping:
	bash components/shipping.sh

payment:
	bash components/payment.sh

dispatch:
	bash components/dispatch.sh

mongodb:
	bash components/mongodb.sh

mysql:
	bash components/mysql.sh

rabbitmq:
	bash components/rabbitmq.sh

redis:
	bash components/redis.sh